stages:
  - check-runner
  - evaluate-run
  - copy-evaluation-to-tira

check-runner:
  stage: check-runner
  image: curlimages/curl
  script:
    - echo "Check that the runner is trustworthy."
    - sleep 10m
    - ./tira-test-runner-is-trustworthy.sh
  tags:
    - no-internet
    
evaluate-run:
  stage: evaluate-run
  script:
    - ls /mnt/ceph/tira/data/
    - ls /mnt/ceph/tira/data/runs/
    - ls /mnt/ceph/tira/data/datasets/test-datasets-truth/
  tags:
    - no-internet
    - read-tira-data-datasets-truth
    - read-tira-data-runs

copy-evaluation-to-tira:
  stage: copy-evaluation-to-tira
  script:
    - echo "This job moves the evaluation result to the TIRA directory. ToDo here, we need write-tira-data-runs"
    - ls /mnt/ceph/tira/data/
    - ls /mnt/ceph/tira/data/runs/
  tags:
    - write-tira-data-runs

