stages:
  - Preparation
  - Run Software
  - Persist Software Result
  - Evaluate Software Result
  - Persist Evaluation Result

prepare-tira-environment:
  stage: Preparation
  image: webis/tira-git:0.0.1
  artifacts:
    reports:
      dotenv: task.env
  script:
    - ./tira-test-runner-is-trustworthy.sh
    - ./tira-specify-task-to-run.sh >> task.env
    - cat task.env
  tags:
    - no-internet

run-user-software:
  stage: Run Software
  dependencies: 
    - prepare-tira-environment
  artifacts:
    untracked: true
    reports:
      dotenv: task.env
  image: "${TIRA_IMAGE_TO_EXECUTE}"
  script:
    - test -n "${TIRA_OUTPUT_DIR}" && mkdir -p ${TIRA_OUTPUT_DIR}
    - echo "${TIRA_COMMAND_TO_EXECUTE}"
    - eval "${TIRA_COMMAND_TO_EXECUTE}"
    - env|grep 'TIRA' >> task.env
  tags:
    - no-internet
    - read-tira-data-datasets-truth
    - read-tira-data-runs

persist-software-result:
  stage: Persist Software Result
  image: webis/tira-git:0.0.1
  artifacts:
    untracked: true
    reports:
      dotenv: task.env
  script:
    - echo "This job moves the software result to the TIRA directory. ToDo here, we need write-tira-data-runs"
    - ls -l .
    - ls /mnt/ceph/tira/data/
    - ls /mnt/ceph/tira/data/runs/
    - echo "${TIRA_COMMAND_TO_EXECUTE}"
    - ls -l /etc/tira-git-credentials
    - cat /etc/tira-git-credentials/GITCREDENTIALPASSWORD
    - cat /etc/tira-git-credentials/GITCREDENTIALUSERNAME
    - env|grep 'TIRA' >> task.env
  dependencies: 
    - run-user-software
  tags:
    - write-tira-data-runs,tira-git-credentials

evaluate-software-result:
  stage: Evaluate Software Result
  dependencies: 
    - persist-software-result
  artifacts:
    untracked: true
    reports:
      dotenv: task.env
  image: "${TIRA_IMAGE_TO_EXECUTE}"
  script:
    - echo "TODO Evaluation"
    - env|grep 'TIRA' >> task.env
  tags:
    - no-internet
    - read-tira-data-datasets-truth
    - read-tira-data-runs

persist-evaluation-result:
  stage: Persist Evaluation Result
  image: webis/tira-git:0.0.1
  script:
    - echo "This job moves the software result to the TIRA directory. ToDo here, we need write-tira-data-runs"
    - ls -l .
    - ls /mnt/ceph/tira/data/
    - ls /mnt/ceph/tira/data/runs/
    - echo "${TIRA_COMMAND_TO_EXECUTE}"
    - ls -l /etc/tira-git-credentials
    - cat /etc/tira-git-credentials/GITCREDENTIALPASSWORD
    - cat /etc/tira-git-credentials/GITCREDENTIALUSERNAME
    - env
  dependencies: 
    - evaluate-software-result
  tags:
    - write-tira-data-runs,tira-git-credentials

