stages:
  - check-runner
  - evaluate-run
  - copy-evaluation-to-tira

check-runner:
  stage: check-runner
  image: curlimages/curl
  artifacts:
    reports:
      dotenv: task.env
  script:
    - ./tira-test-runner-is-trustworthy.sh
    - ./tira-specify-task-to-run.sh >> task.env
    - cat task.env
  tags:
    - no-internet

evaluate-run:
  stage: evaluate-run
  dependencies: 
    - check-runner
  artifacts:
    untracked: true
    reports:
      dotenv: task.env
  image: "${TIRA_IMAGE_TO_EXECUTE}"
  script:
    - mkdir -p ${TIRA_OUTPUT_DIR}
    - echo "${TIRA_COMMAND_TO_EXECUTE}"
    - eval "${TIRA_COMMAND_TO_EXECUTE}"
    - env|grep 'TIRA' >> task.env
  tags:
    - no-internet
    - read-tira-data-datasets-truth
    - read-tira-data-runs
  rules:
    - if: $TIRA_IMAGE_TO_EXECUTE

copy-evaluation-to-tira:
  stage: copy-evaluation-to-tira
  script:
    - echo "This job moves the evaluation result to the TIRA directory. ToDo here, we need write-tira-data-runs"
    - ls -l .
    - ls /mnt/ceph/tira/data/
    - ls /mnt/ceph/tira/data/runs/
    - echo "${TIRA_COMMAND_TO_EXECUTE}"
  dependencies: 
    - evaluate-run
  tags:
    - write-tira-data-runs
  rules:
    - if: $TIRA_OUTPUT_DIR

