stages:
  - check-runner
  - evaluate-run
  - copy-evaluation-to-tira

check-runner:
  stage: check-runner
  image: curlimages/curl
  artifacts:
    reports:
      dotenv: task.env
  script:
    - ./tira-test-runner-is-trustworthy.sh
    - ./tira-specify-task-to-run.sh >> task.env
  tags:
    - no-internet

evaluate-run:
  stage: evaluate-run
  dependencies: 
    - check-runner
  artifacts:
    untracked: true
  image: "${IMAGE_TO_EXECUTE}"
  script:
    - mkdir -p ${OUTPUT_DIR}
    - echo "${COMMAND_TO_EXECUTE}"
    - eval "${COMMAND_TO_EXECUTE}"
  tags:
    - no-internet
    - read-tira-data-datasets-truth
    - read-tira-data-runs

copy-evaluation-to-tira:
  stage: copy-evaluation-to-tira
  script:
    - echo "This job moves the evaluation result to the TIRA directory. ToDo here, we need write-tira-data-runs"
    - ls -l .
    - ls /mnt/ceph/tira/data/
    - ls /mnt/ceph/tira/data/runs/
  dependencies: 
    - evaluate-run
  tags:
    - write-tira-data-runs

