# our gitlab
gitlabUrl: https://git.webis.de

# I got this registration token from the "Settings" -> "CI/CD Settings" -> "Runners" -> "Specific runners" section
runnerRegistrationToken: GR1348941n1xMSpZPmyp3voJLGpAU

# The runner uses this service account to create pods.
rbac:
  serviceAccountName: tira-runner-service-account-in-kibi9872

runners:
  name: gitlab-gitlab-runner-tira-copy
  Description: Copy runs from user software or evaluators to TIRA.
  tags: write-tira-data-runs
  config: |
    [[runners]]
      [runners.kubernetes]
        image = "ubuntu:16.04"
        [[runners.kubernetes.volumes.host_path]]
          name = "read-tira-data-datasets-test-datasets"
          mount_path = "/mnt/ceph/tira/data/runs/"
          read_only = false
          host_path = "/mnt/ceph/storage/data-tmp/current/kibi9872/tira-dummy-repository/data/runs/"
